### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JayLi1209** [GitHubNoskcaj211/EnrollmentBot#1]
Thank you for this amazing work! 
However, I'm getting Errors when unpacking this app, although I have granted access and everything. I have also tried appending my commodore ID as appeared in the url, but still it won't resolve. Will this error affect the use?

Will donate if it works!
Y. Li, the clarinetist from VCO :)

<img width="664" alt="Screen Shot 2023-10-30 at 10 49 24 AM" src="https://github.com/GitHubNoskcaj211/EnrollmentBot/assets/100735820/0c64e415-7d81-4910-b885-da793f0be80d">

**Comment by GitHubNoskcaj211** [comment]
Hey - sorry I didn't see this... Was this resolved / did you do anything to fix this? I'm thinking this might be Chrome version issues

**Comment by JayLi1209** [comment]
Hi! It's showing as error, but it's actually working.

**Comment by GitHubNoskcaj211** [comment]
Looked into this... the host permissions were erroring because they had a specific section in chrome manifest v3. These permissions were not needed (hence why the extension continued to work).
Updated to remove the unnecessary permissions.
https://www.extension.ninja/blog/post/solved-permission-is-unknown-or-url-pattern-is-malformed/
